- name: Copy cert and private key to the host
  block:
    - name: Create a tempfile for the {{ item }} file on the host
      tempfile:
        state: file
      register: __mssql_cert_tempfile

    - name: Copy the {{ item }} file to the host
      copy:
        src: "{{ item }}"
        dest: "{{ __mssql_cert_tempfile.path }}"
        owner: mssql
        group: mssql
        mode: 0600

    - name: Move the cert file to the appropriate location
      copy:
        remote_src: true
        src: "{{ __mssql_cert_tempfile.path }}"
        dest: /etc/pki/tls/certs/{{ item | basename }}
        owner: mssql
        group: mssql
        mode: 0600
        force: true
      when: item == mssql_tls.cert

    - name: Move the private key file to the appropriate location
      copy:
        remote_src: true
        src: "{{ __mssql_cert_tempfile.path }}"
        dest: /etc/pki/tls/private/{{ item | basename }}
        owner: mssql
        group: mssql
        mode: 0600
        force: true
      when: item == mssql_tls.private_key

  always:
    - name: Remove the tempfile
      file:
        path: "{{ __mssql_cert_tempfile.path }}"
        state: absent
