- name: Check if the {{ __mssql_conf_setting }} setting is enabled
  command: /opt/mssql/bin/mssql-conf get {{ __mssql_conf_setting }}
  ignore_errors: true
  changed_when: false
  register: __mssql_conf_get_setting

- name: Configure the {{ __mssql_conf_setting }} setting
  command: >-
    /opt/mssql/bin/mssql-conf set {{ __mssql_conf_setting }}
    {{ __mssql_conf_setting_value }}
  when: >-
    ("No setting for the given" in __mssql_conf_get_setting.stdout)
    or (__mssql_conf_setting_value | string | lower not in
    __mssql_conf_get_setting.stdout | lower)
  register: __mssql_conf_set
  failed_when: '"error" in __mssql_conf_set.stdout | lower'
  notify: Restart the mssql-server service
