# SPDX-License-Identifier: MIT
---
- name: Restart the mssql-server service
  service:
    name: mssql-server
    state: restarted
  when: not (__mssql_primary_restarted is changed or
    __mssql_replica_restarted is changed)
